---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitalicloud-app
  labels:
    app: aitalicloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aitalicloud-app
  template:
    metadata:
      labels:
        app: aitalicloud-app
    spec:
      containers:
      - name: aitalicloud-container
        image: 123456789123.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
